### ISSUE TITLE
PoC Module inter-dependency

### ISSUE THREAD

**Issue by rahalan** [Azure/ResourceModules#905] opened 2022-01-19 15:08 UTC
Currently every module brings, if necessary, it own modules with it, if they are needed. For example VM, Azure Firewall and some others can create their own Public IP address. But we also have a stand alone PIP module. The question is, should we only use the stand-alone module and add dependencies between the modules, or should we keep them atomic with the drawback, that one change to PIP for example, needs to be done on all modules that create a PIP. Currently the PIP code is always a bit different, which already shows, we have an issue here.

The PoC should investigate how a local reference (inside the repo) can work.

**Comment by eriqua** [comment] 2022-04-26 11:11
Is this related/duplicate of #400 ?

**Comment by MrMCake** [comment] 2022-05-17 17:13
Links to
- #1271 
- #1255 
- #1254

**Closed** 2022-05-29 22:22 UTC
Labels: enhancement
