### ISSUE TITLE
Module readmes - Autogenerate the `parameter usage` sections in the module readme

### ISSUE THREAD

**Issue by MariusStorhaug** [Azure/ResourceModules#1246] opened 2022-04-12 03:38 UTC
## Description

To avoid untested examples going into the module readme, we should attempt to autogenerate the `Parameter Usage` section from the readme to ensure the examples are actually working.

These should preferably be in both bicep and json format. Bicep first as that is what you would rely on when creating solutions.

See #1245 for more info on errors caused by templated/manually created param usage examples.
See #1179 for the task on generating this for bicep.
See #1227 for adding examples to the readme

**Comment by MrMCake** [comment] 2022-05-12 15:46
Should also fail on too many blocks (a block for a parameter that does not exist)

**Comment by MrMCake** [comment] 2022-06-25 19:03
Duplicate of #1096?

**Comment by AlexanderSehr** [comment] 2023-07-21 17:44
Closing in favor of the work for user-defined types.

**Closed by AlexanderSehr** 2023-07-21 17:44 UTC
Labels: documentation, enhancement, [cat] modules, [cat] testing, workshop feedback
