### ISSUE TITLE
[Failed pipeline] Insights: DataCollectionRules

### ISSUE THREAD

**Issue by rahalan** [Azure/ResourceModules#2651] opened 2023-02-04 05:36 UTC
failed run: https://github.com/Azure/ResourceModules/actions/runs/4086938800

**Comment by rahalan** [comment] 2023-02-06 05:34
failed run: https://github.com/Azure/ResourceModules/actions/runs/4095992200

**Comment by krbar** [comment] 2023-02-20 07:56
Looks like a duplicate of #2776, which has been fixed by #2809. Probably the issue can be closed.

**Comment by krbar** [comment] 2023-02-20 16:02
Fixed by #2809, closing.

**Closed by krbar** 2023-02-20 16:02 UTC
Labels: bug, automation
