### ISSUE TITLE
[Bug Report]: Log Analytics workspaces etag field not valid

### ISSUE THREAD

**Issue by itpropro** [Azure/ResourceModules#1570] opened 2022-06-21 21:32 UTC
### Describe the bug

When deploying a log analytics workspace using the `Microsoft.OperationalInsights/workspaces` module, the following warning appears:
`E:\repos\test\modules\carml\0.5.0\Microsoft.OperationalInsights\workspaces\savedSearches\deploy.bicep(55,5) : Warning BCP037: The property "etag" is not allowed on objects of type "SavedSearchProperties". No other properties are allowed. If this is an inaccuracy in the documentation, please report it to the Bicep Team. [https://aka.ms/bicep-type-issues]`

If this can be confirmed to be an error, it should be enough to remove the following lines:
https://github.com/Azure/ResourceModules/blob/7eaa7edfc07f7db4fe5e255f07ebc22175777918/arm/Microsoft.OperationalInsights/workspaces/deploy.bicep#L206
https://github.com/Azure/ResourceModules/blob/7eaa7edfc07f7db4fe5e255f07ebc22175777918/arm/Microsoft.OperationalInsights/workspaces/savedSearches/deploy.bicep#L55

### To reproduce

Deploy a log analytics workspace using the Microsoft.OperationalInsights/workspaces module.

**Comment by itpropro** [comment] 2022-06-22 10:48
I'll be happy to leave a PR, if this is a confirmed issue.

**Comment by MrMCake** [comment] 2022-06-23 09:07
Hey @itpropro, I actually brought this up [with the PG](https://github.com/Azure/bicep/issues/784#issuecomment-1140499904) some time back. 

Long story short, it seems to be a provider inaccuracy. The API tells you to place the `etag` outside the `param` block, but if you do that, the deployment doesn't work. It does however inside the block.

This was originally introduced by @SeSeicht in this PR: #1413.

**Comment by justinkhart** [comment] 2022-06-24 05:10
I can confirm that moving the etag inside the properties object does allow a deployment, the warning is definitely incorrect. Adding the etag property allows me to redeploy the hunting rule without any errors in Azure. 

Couple screenshots if they help. 
![image](https://user-images.githubusercontent.com/14272967/175466306-1460c7ba-3f27-4980-bbe7-4edfe99311f2.png)

![image](https://user-images.githubusercontent.com/14272967/175466327-42c2bc92-2b25-4423-859a-aeb790475726.png)

**Comment by itpropro** [comment] 2022-06-25 12:19
Thanks for the explanation, where is the issue tracked with the Bicep team @MrMCake ?

**Comment by MrMCake** [comment] 2022-06-25 18:48
Hey @itpropro , I raised the issue in the 'offical' "Missing type validation / inaccuracies" issue [here](https://github.com/Azure/bicep/issues/784#issuecomment-1140499904) (just expand `Microsoft.OperationalInsights/workspaces/savedSearches`).

There have also been a couple comments to it underneath.

**Comment by MrMCake** [comment] 2022-09-09 09:30
I'll go ahead and close this issue here as fixing it appears to be outside of CARML's reach and something either the ARM/Bicep PG or the Provider-PG have to fix on their end.

**Closed by MrMCake** 2022-09-09 09:30 UTC
Labels: bug
