### ISSUE TITLE
[Bug Report]: New Diagnostic settings do not support retention

### ISSUE THREAD

**Issue by chris-gibbs** [Azure/ResourceModules#3572] opened 2023-08-13 10:39 UTC
### Describe the bug

Receiving an error when trying to deploy a storage account with Diagnostic settings enabled.

I believe it may be related the timelines identified in 
https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/migrate-to-azure-storage-lifecycle-policy

Will need a fix for storage account, blob, file, table and queue.

Currently I'm just commenting out but will most likely need further work to clean up old params no longer required.

```Bicep
var diagnosticsMetrics = [for metric in diagnosticMetricsToEnable: {
  category: metric
  timeGrain: null
  enabled: true
  // https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/migrate-to-azure-storage-lifecycle-policy
  //retentionPolicy: {
  //  enabled: true
  //  days: diagnosticLogsRetentionInDays
  //}
}]
```

### To reproduce

Deploy storage with Diagnostic settings enabled

### Relevant log output

```Shell
{
  "code": "BadRequest",
  "message": "Diagnostic settings does not support retention for new diagnostic settings."
}
```

**Comment by johnparkpq** [comment] 2023-08-14 07:27
Same issue with the /network/network-interfaces and /network/public-ip-addresses modules when deploying VMs.
Commented out retentionPolicy sections in the above modules as suggested by @chris-gibbs as a workaround.

**Comment by AlexanderSehr** [comment] 2023-08-16 11:14
Hey @chris-gibbs & @johnparkpq , thanks for raising this. I'll take a closer look how to best solve this but would in general suggest to not fix it just for 1, 2 or 3 modules, but for all in one go (assuming that all Providers are supporting the lifecylce changes).

**Comment by joehubbert** [comment] 2023-08-23 09:52
Hi @AlexanderSehr I just noticed this issue today, is there a fix planned for this?

**Comment by AlexanderSehr** [comment] 2023-08-23 18:27
> Hi @AlexanderSehr I just noticed this issue today, is there a fix planned for this?

Hey @joehubbert, not yet planned, but it should be fixed. I'm currently on vacation and hence didn't have a closer look yet. I will however try once I'm back next week.

**Comment by rezamanshouri** [comment] 2023-08-23 18:31
Encountered the same problem for Storage Account (blob and queue), Event Grid, and cosmos DB.

**Comment by VanathiGanesh** [comment] 2023-08-23 23:47
Our team is encountering the same issue - when can we expect a fix?

**Comment by Mercy-Markus** [comment] 2023-08-24 08:26
Same for my team as well. We have diagnostic settings enable on our App Services.

**Comment by DenisBalan** [comment] 2023-08-24 10:42
Same problem, any eta? was there any information about this deprecation prior to this?

For us, its a major impact as the infrastructure that we provision, suddently fails for all types of resources that had `retentionPolicy` enabled from terraform.

Thanks.

**Comment by rezamanshouri** [comment] 2023-08-24 19:38
Looks like this is the new expected behavior (they just missed the deadline): https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/migrate-to-azure-storage-lifecycle-policy

**Comment by jensdiedrich** [comment] 2023-08-25 13:13
If you change

`diagnosticLogsRetentionInDays` to `0` it seems to work.
Maybe a quick workaround until it´s fixed.

**Comment by AlexanderSehr** [comment] 2023-08-26 07:55
Hey folks,
I started working on a Pull Request #3721 .
If I understand it correctly, all it takes is to remove the `retentionPolicy` as a default settings from the corresponding deploment templates and use the storage account's `managementPolicyRules` going forward (both deployments work). 
As I'm no expert in the matter and may miss something, could you provide me with feedback on this assumption? Ideally even on the Pull Request itself.

**Closed** 2023-08-28 20:44 UTC
Labels: bug

**Comment by Ryangr0** [comment] 2023-08-31 09:30
Are you kidding me? Deprecation without any notice and a month early... I almost can't believe it. Do you guys realize this kind of stuff is literally breaking prod for your users? This is now the XXth time I'm running into this kind of thing the last few months. The migration guide is atrociously bad and doesn't address setups with proper IAAC approaches...

**Comment by AlexanderSehr** [comment] 2023-08-31 18:33
Hello @Ryangr0, 

I just saw your comment, and (as a maintainer) quickly wanted to take the timeto respond to your feedback. I assume you're **not** referring to the Diagnostic-Setting change (in Azure) itself, but the change in this repository (i.e., the linked PR)? I'm just asking because I cannot speak for the former and can only say it appeared to have been announced some time back, given the introduction in the docs.

Anyways, regarding your experience with this repository I can only say sorry that your experience over the last months has been so bad - and I'll take personal responsiblity for that as I myself worked on most of those breaking changes to somehow hit an upcoming deadline for the Public Registry migration. 
What we opted to do as a heads up for the bumpy ride, was to post a [warning](https://github.com/Azure/ResourceModules#upcoming-breaking-changes) on the front page about 4 months back to warn about the breaking changes we were asked to implement, and tag an issue related to this in the issues page. I'm no GitHub expert, so maybe there would have been another way to tell people in advance that changes are coming and that it's probably worth waiting for the next release with most, if not all, breaking changes were implemented.

I know that it's likely no condolence to say 'just wait for the next release' since (for capacity reasons) we're not creating monthly releases and 'waiting' for 4 months isn't exactly a short timespan. As far as I'm concerned, I'd have like to create way more frequent releases, but with the amount of breaking changes that were asked of us, we opted to rather implement them in one go / release, instead of asking users with each release to migrated from one breaking change to the next.

Also please note, this repository is run by a number of community members inside and outside of Microsoft. We are no product group and, as we're all doing this on top of our day-to-day job, we can not provide a strict SLA as per our [support statement](https://github.com/Azure/ResourceModules/blob/main/SUPPORT.md). We further [advice](https://github.com/Azure/ResourceModules#disclaimer) in general against pulling directly from main - in case this is what you're refering to with 'breaking production'.

Again, it is definitely not my, or the rest of the contributors, motivation to give anybody a bad time using this repository. We try our best to continuously evolve both the CI environement and the modules, contribute our learnings - or even correct some odd misalignments of the resource providers (#CMK), and overall share what we can with the general public to enable others to benefit from it. The diagnostic change in particular started failing 60+ module pipelines (the ones that supported diagnostics), so while you're right that this change may have come early, the alternative would have been to not test those modules in our CI anymore (or disable the test itself). Right before our next, and library-wise likely last release, this was not an option.

Most changes can lead to smaller or bigger breaking changes (e.g., just a single module, mutliple modules, or the CI), and as we're getting contributions from a large amount of contributors, we simply don't have the capacity to provide anything but the _atrociously bad_ migration guide. Or rather, we tried, and failed. 

The alternative would have been to inner-source the project entirely, and if that is considered the better alternative, so be it. With our currently available capacity we (or at least I for my part) cannot offer more. 

All that said, there is hope. As I pointed out earlier, we're not implementing all these changes for the fun of it. In the short- / mid-term, there will be a large-scale migration of the library (not the CI) from this repository into the [Public Bicep Registry](https://github.com/Azure/bicep-registry-modules). This comes we with benefit for the community, that we will not only be able to version modules individually (for those directly using them) - but also scale better by having dedicated individuals 'owning' and maintaining registry modules.

While all this does obviously not solve your issues, I hope I was at least able to provide some subjective context as to why certain things went the way they did and give a short outlook, where things are moving. Please feel free to reach out if I raised more questions than provided answers.

**Comment by alexwhitmore** [comment] 2023-09-01 13:35
According to the migration guide, it is a pre-requisite to send your storage account diagnostic setting logs to a storage account container. If I want to continue sending logs to the Log Analytics Workspace, is there a different migration guide? If I keep my set up as it (sending logs to LAW), and remove the retentionPolicy, I would just retain the logs indefinitely, right?

**Comment by AlexanderSehr** [comment] 2023-09-01 14:44
> According to the migration guide, it is a pre-requisite to send your storage account diagnostic setting logs to a storage account container. If I want to continue sending logs to the Log Analytics Workspace, is there a different migration guide? If I keep my set up as it (sending logs to LAW), and remove the retentionPolicy, I would just retain the logs indefinitely, right?

Hey @alexwhitmore, to my understanding, this change 'only' affects the StorageAccount target for Diagnostic Settings and none of the other options (e.g. LogAnalytics, EventHub, etc.).

Whether Logs are stored indefinitely in the StorageAccount that backs up the LogAnalyticsWorkspace (and is invisible to us) is a different question and would require a readup on the corresonding docs. I would however assume that there is a maximum rention time in LAW and that, if you want to store logs idenfinitely, you'd need to send them to a custom storage acocunt too (e.g., with an archive tier). Take this statement with a grain of salt though, as this is just my expectation, without having looked deeper into it.

**Comment by alexwhitmore** [comment] 2023-09-05 14:53
> > According to the migration guide, it is a pre-requisite to send your storage account diagnostic setting logs to a storage account container. If I want to continue sending logs to the Log Analytics Workspace, is there a different migration guide? If I keep my set up as it (sending logs to LAW), and remove the retentionPolicy, I would just retain the logs indefinitely, right?
> 
> Hey @alexwhitmore, to my understanding, this change 'only' affects the StorageAccount target for Diagnostic Settings and none of the other options (e.g. LogAnalytics, EventHub, etc.).
> 
> Whether Logs are stored indefinitely in the StorageAccount that backs up the LogAnalyticsWorkspace (and is invisible to us) is a different question and would require a readup on the corresonding docs. I would however assume that there is a maximum rention time in LAW and that, if you want to store logs idenfinitely, you'd need to send them to a custom storage acocunt too (e.g., with an archive tier). Take this statement with a grain of salt though, as this is just my expectation, without having looked deeper into it.

If this change only affects the StorageAccount target for Diagnostic Settings, then I'm assuming removing the retention parameter would prevent my deployment from failing, however that would store the logs in LAW indefinitely - which is not the desired outcome. 

Let's say my storage account logs are sent to the LAW, and I want these logs to be deleted after 365 days. Now that I can't directly set the retention policy, do I still need to implement the Azure Storage Lifecycle Policy? 

As far as I understand, when setting up the lifecycle policy I can only filter for storage account containers which would completely ignore my LAW.

I apologize in advance if this isn't the place to drop these questions!

**Comment by khaliddermoumi** [comment] 2023-09-05 17:30
> Hello @Ryangr0,
> 
> (...) What we opted to do as a heads up for the bumpy ride, was to post a [warning](https://github.com/Azure/ResourceModules#upcoming-breaking-changes) on the front page about 4 months back to warn about the breaking changes we were asked to implement, and tag an issue related to this in the issues page. I'm no GitHub expert, so maybe there would have been another way to tell people in advance that changes are coming and that it's probably worth waiting for the next release with most, if not all, breaking changes were implemented.
> (...)  As far as I'm concerned, I'd have like to create way more frequent releases, but with the amount of breaking changes that were asked of us, we opted to rather implement them in one go / release, instead of asking users with each release to migrated from one breaking change to the next.

BTW a well-known convention to communicate coming breaking changes is to increment the major version number, if you're using semver anyway (version number format "v0.10.0" implies semver). The dev team collects "breaking change requests" for some time, while they make only small compatible releases. When there's enough breaking change requests, they make a breaking release with the major version number bumped. Of course that doesn't work if you choose to stay on v0.x.y all the time. More frequent releases are helpful for this.
In addition, a changelog is really helpful too.

**Comment by AlexanderSehr** [comment] 2023-09-05 18:48
> > Hello @Ryangr0,
> > (...) What we opted to do as a heads up for the bumpy ride, was to post a [warning](https://github.com/Azure/ResourceModules#upcoming-breaking-changes) on the front page about 4 months back to warn about the breaking changes we were asked to implement, and tag an issue related to this in the issues page. I'm no GitHub expert, so maybe there would have been another way to tell people in advance that changes are coming and that it's probably worth waiting for the next release with most, if not all, breaking changes were implemented.
> > (...)  As far as I'm concerned, I'd have like to create way more frequent releases, but with the amount of breaking changes that were asked of us, we opted to rather implement them in one go / release, instead of asking users with each release to migrated from one breaking change to the next.
> 
> BTW a well-known convention to communicate coming breaking changes is to increment the major version number, if you're using semver anyway (version number format "v0.10.0" implies semver). The dev team collects "breaking change requests" for some time, while they make only small compatible releases. When there's enough breaking change requests, they make a breaking release with the major version number bumped. Of course that doesn't work if you choose to stay on v0.x.y all the time. More frequent releases are helpful for this. In addition, a changelog is really helpful too.

Agreed and will be the case post the Public Bicep Registry migration. Will also be a lot better to manage as we can version on a per-module basis instead of 'all in one'.
