### ISSUE TITLE
Role Assignments Platform Dependency 

### ISSUE THREAD

**Issue by cacarroll** [Azure/ResourceModules#450] opened 2021-11-10 10:57 UTC
This appears to work the first time but subsequent runs result in an error.    

  | 18:16:21 - The deployment
     | 'roleAssignments-20211107T1811318847Z' failed with error(s).
     | Showing 1 out of 1 error(s). Status Message: The role
     | assignment already exists. (Code:RoleAssignmentExists) 
     | CorrelationId: 857164a2-a31a-4d4c-9bab-9c19239cb5be

**Comment by rahalan** [comment] 2021-11-15 15:12
@eriqua for me it looks like, that is working in our environment. Do you have an idea, why it failed for @cacarroll ?

**Comment by ahmadabdalla** [comment] 2021-12-01 21:00
@cacarroll , can you please do a fetch and see if the issue is still present. We’ve recently updated most modules part of the 0.3 release. Thanks

**Comment by MrMCake** [comment] 2022-03-02 07:22
Closing as there was no progress in 3 months

**Closed by MrMCake** 2022-03-02 07:22 UTC
Labels: bug
