### ISSUE TITLE
Public IP - Ensure that all module that require a PIP, can deploy it

### ISSUE THREAD

**Issue by MariusStorhaug** [Azure/ResourceModules#1272] opened 2022-04-13 06:08 UTC
## Description

Public IP should be able to be created in each module that requires one without a separate module deployment
E.g. Azure Firewall doesn’t support this today, but Virtual Network Gateways do

**Comment by jontreynes** [comment] 2022-05-17 19:45
this is a duplicate of #1154

**Closed by jontreynes** 2022-05-17 19:45 UTC
Labels: enhancement
