### ISSUE TITLE
[Bug Report]: v0.10.0 breaks deployments with existing Resource Groups (deployed with CARML <= 0.9.0)

### ISSUE THREAD

**Issue by zydio** [Azure/ResourceModules#3444] opened 2023-07-25 15:12 UTC
### Describe the bug

Release **0.10.0** shows the following entry in the **_Fixes_** section:

- Update Resource Group roleAssignments name (GUID) to use Resource Group resourceID instead of Resource Group name

There are two problems:

1. This is a **Breaking Change** and this is not advertised in the release notes
2. This is a **Breaking Change** and makes it impossible to successfully run a deployment including existing Resource Groups that were first deployed with BICEPs using CARML <= 0.9.0

Looking in the repo history, this change comes from PR https://github.com/Azure/ResourceModules/pull/2642 , which is actually marked as containing **Breaking change**

Regarding point 2, if you have deployed resource groups with role assignments with CARML <= 0.9.0, and you try to run a deployment again of the same BICEP with CARML 0.10.0 you get a conflict with error _The role assignment already exists._ and the deployment fails.
ARM is right to complain, because the assignment exists but with a different GUID as a name.

New BICEP compile versions (for sure from 0.15.31 onwards) don't complain anymore for the error shown in the ticket.
That line should be changed to something like:
`useLegacyRoleAssignmentNaming ? guid(last(split(resourceId, '/')), principalId, roleDefinitionIdOrName) : guid(resourceId, principalId, roleDefinitionIdOrName)`

And a `useLegacyRoleAssignmentNaming` param should be added to **modules\Microsoft.Resources\resourceGroups\.bicep\nested_roleAssignments.bicep** and surfaced in **modules\Microsoft.Resources\resourceGroups\deploy.bicep** so that ARM can handle new deployments on existing resources deployed with old versions.

### To reproduce

Deploy a Resource Group with the CARML module <= 0.9.0 and specify a Role Assignment on the Resource Group.

Update CARML to 0.10.0 and run the same deployment: it will fail with error _The role assignment already exists._

### Code snippet

```Bicep
module resourceGroups 'CARML/modules/Microsoft.Resources/resourceGroups/deploy.bicep' = {
  name: '${uniqueString(deployment().name)}-ResourceGroup-test'
  params: {
    name: 'breaking-change-test-rg'
    location: 'westeurope'
    roleAssignments: [
        {
          principalIds: [
             // ..Write here a principalId..
          ]
          roleDefinitionIdOrName: 'Reader'
        }
      ]
    }
  }
  
}]
```

### Relevant log output

```Shell
The role assignment already exists.
```

**Comment by eriqua** [comment] 2023-07-27 17:09
Hi @zydio, thanks for pointing this out. 

While breaking changes are not ideal, we had to introduce this one for three main reasons:

1. Following RBAC name best practices (ref [Create Azure RBAC resources by using Bicep](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/scenarios-rbac#name) ) 
2. Consistency with nested RBAC implementation at resource level for other modules
3. Fixing an error thrown by the Bicep compiler once upgrading Bicep to release 0.14.6
`Argument of type "null | string" is not assignable to parameter of type "string".bicep(BCP070)`

You may ref to PR #2642 introducing this change, for additional context.

To solve the already existing role assignment, a possible workaround would be to delete the Azure role assignment and redeploy the solution using the new module. Would that be feasible in your scenario?

Please let us know if that helps!

**Comment by AlexanderSehr** [comment] 2024-06-15 15:36
I'll close this issue in favor of https://github.com/Azure/bicep-registry-modules/issues/2008 as it's implementation will provide a workaround via a configurable role assignment GUID. Truth be told, it's not comprehensable why the role assignment resource provider would have this limitation to begin with - and I sincerely hope it will be addressed in the future.

That being said, to also address CARML's tendency to introduce breaking changes without adding backwards-compatibility flags - this is 'somewhat' by design. The module's in CARML were always intended to shared the latest version of modules that we and others may be using when deploying infrastructure. The version.json file alongside the CI where hence intended to inner-source the library and use it from there on out - and by being open-source, allowing users to modify the module source-code as they see fit.
I know, that makes the 'issue' really easy for us to ignore, but considering the opposite - that is, to provide backwards compatibility for every breaking change for an abstraction layer that is built on top of an Infrastructure-as-Code language can render the code eventually extremly hard to maintain / too complex to use. Can't say I see a clear good solution for the matter.

**Closed by AlexanderSehr** 2024-06-15 15:36 UTC
Labels: bug, wait for author
