### ISSUE TITLE
[Bug Report]: Minor bug in key vault's diagnostic settings name

### ISSUE THREAD

**Issue by khaliddermoumi** [Azure/ResourceModules#1458] opened 2022-06-01 11:49 UTC
### Describe the bug

The diagnostic settings name in the key vault module (git tag v0.5.0) is:
```bicep
 '${name_var}-diagnosticSettingName'.
```
The intention was obviously:
```bicep
'${name_var}-${diagnosticSettingsName}'
```
There is also a now unused variable "diagnosticSettingsName", which would make sense if it was used in the name.

### To reproduce

Create a key vault with the v0.5.0 version of the module.

### Code snippet

```Bicep
(omitted, just the plain vanilla usage of the module)
```

### Relevant log output

```Shell
C:\...\ResourceModules\arm\Microsoft.KeyVault\vaults\deploy.bicep(124,7) : Warning no-unused-params: Parameter "diagnosticSettingsName" is declared but never used. [https://aka.ms/bicep/linter/no-unused-params]
```

**Comment by akata72** [comment] 2022-06-02 19:34
I believe this was already fixed in the latest version? or do you still see this issue in the latest version of the file.

**Comment by MrMCake** [comment] 2022-06-04 10:13
I was fixed in that the variable is now used. However, the solution isn't ideal as @khaliddermoumi correctly pointed out it should reference `${name_var}` in the diagnostic settings name. The problem is, this value is a variable and not available for a default value of a parameter.
Anyhow, this issue may resolve itself following #1443 .

**Comment by rahalan** [comment] 2022-06-07 16:05
See #1443 - depends on that issue.

**Closed as completed** 2022-09-01 09:01 UTC
Labels: bug
