### ISSUE TITLE
Module readmes - Test and update parameter usage section in readme in all modules

### ISSUE THREAD

**Issue by MariusStorhaug** [Azure/ResourceModules#1245] opened 2022-04-12 03:33 UTC
## Description

During a workshop on CARML, teams used the parameter usage sections when creating solutions. Some of these were incorrect, causing the teams to need to check the code for actual parameter usage, thus slowing them down. These parameter usage examples needs to be tested and validated and updated where needed to ensure they are correct.

**Comment by MrMCake** [comment] 2022-09-30 12:29
Linked to #1096

**Comment by eriqua** [comment] 2022-10-05 21:16
I also would suggest to close this issue as a duplicate of #1096. Moving back to needs triage for this purpose.

**Closed** 2022-10-11 16:05 UTC
Labels: documentation, enhancement, [cat] modules, [cat] testing, workshop feedback
