### ISSUE TITLE
'templateSpecName' exceeds maximum length of '90'.

### ISSUE THREAD

**Issue by akata72** [Azure/ResourceModules#1432] opened 2022-05-25 05:32 UTC
### Describe the bug

When trying to publish a prerelease of the recoveryservicesvault module I ran into this limitation. Might need some logic to verify and truncate somehow if length exceeds this limitation of 90??.

`VERBOSE: Performing the operation "Publish" on target "Template spec [microsoft.recoveryservices.vaults.replicationfabrics.replicationprotectioncontainers.replicationprotectioncontainermappings] version [0.1.645-prerelease]".
VERBOSE: Using Bicep v0.6.18
WARNING: /home/vsts/work/1/s/arm/Microsoft.RecoveryServices/vaults/replicationFabrics/replicationProtectionContainers/replicationProtectionContainerMappings/deploy.bicep(33,39) : Warning prefer-interpolation: Use string interpolation instead of the concat function. [https://aka.ms/bicep/linter/prefer-interpolation]
New-AzTemplateSpec: /home/vsts/work/1/s/utilities/pipelines/resourcePublish/Publish-ModuleToTemplateSpec.ps1:83
Line |
  83 |              New-AzTemplateSpec @templateSpecInputObject -Force
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 'templateSpecName' exceeds maximum length of '90'.
`

### To reproduce

Publish the recoveryservicesvault to templatespec.

**Comment by MrMCake** [comment] 2022-05-26 09:57
This is a duplicate of bug #1172 . @akata72 please feel free to add you thoughts to that issue. We have a couple ideas on the table and would appreciate as many thoughts as possible.

**Closed by MrMCake** 2022-05-26 09:57 UTC
Labels: bug
