### ISSUE TITLE
Module: Align all modules regarding their deployment names

### ISSUE THREAD

**Issue by MrMCake** [Azure/ResourceModules#652] opened 2021-11-29 10:25 UTC
Module: Align all modules regarding their deployment names. Right now a lot of modules diverge from what was agreed upon in the [wiki](https://github.com/Azure/ResourceModules/wiki/ModulesDesign#child-resources-naming). This should be accounted for.

**Comment by eriqua** [comment] 2021-11-29 10:29
@MrMCake isn't this a duplicate of #472?

**Closed** 2021-11-29 10:33 UTC
Labels: duplicate, enhancement, [cat] modules
