### ISSUE TITLE
[Bug Report]: Management Group Deployment not working

### ISSUE THREAD

**Issue by MrMCake** [Azure/ResourceModules#1342] opened 2022-04-27 07:13 UTC
### Describe the bug

The current module implementation does not work as the RBAC deployment assumes that the (to be created) management group already exists when you start the deployment. This already happens with the `Test-AzManagementGroupDeployment` command.

The error is: `ManagementGroupNotFound - The management group 'testMG' cannot be found.`

The `testMG` is the one that is to be deployed as per the parameter file.

The code snipped that produces the error:

```bicep
module managementGroup_rbac '.bicep/nested_rbac.bicep' = [for (roleAssignment, index) in roleAssignments: {
  name: '${uniqueString(deployment().name)}-ManagementGroup-Rbac-${index}'
  params: {
    description: contains(roleAssignment, 'description') ? roleAssignment.description : ''
    principalIds: roleAssignment.principalIds
    principalType: contains(roleAssignment, 'principalType') ? roleAssignment.principalType : ''
    roleDefinitionIdOrName: roleAssignment.roleDefinitionIdOrName
    resourceId: managementGroup.id
  }
  scope: managementGroup
}]
```

The `nested_rbac.bicep` implementation seems fine and matches 1:1 the `Microsoft.Authorization/roleAssignments/managementGroup` (working) example.

> **Note:** It seems that there might be a Bicep bug in that the language does not understand how to deal with a management group if you set it as the scope. I already tried different solutions like changing the scopes inside & outside the bicep template, using an extra level of nesting to do the same - all to not avail.

### To reproduce

Run a `Test-AzManagementGroupDeployment`

### Code snippet

```Bicep
Execute

> Test-AzManagementGroupDeployment -TemplateParameterFile .\Microsoft.Management\managementGroups\.parameters\parameters.json' -TemplateFile '.\Microsoft.Management\managementGroups\deploy.bicep' -Verbose -ManagementGroupId '<<managementGroupId>>' -Location 'WestEurope'

using the standard parameter file.
```

**Comment by eriqua** [comment] 2022-06-16 15:05
Is this issue on the Bicep team? Should we put it as blocked? 
Alternatively, if the issue is on the rbac, should we discuss if removing the rbac property for now to have at least the MG module working?

**Comment by MattLeach25** [comment] 2022-06-17 07:06
> Is this issue on the Bicep team? Should we put it as blocked? Alternatively, if the issue is on the rbac, should we discuss if removing the rbac property for now to have at least the MG module working?

Yeah maybe we should comment out the RBAC bit for now until we get a response back from the Bicep team. @MrMCake are you happy with this approach?

**Comment by eriqua** [comment] 2022-07-09 18:12
RBAC has been removed from the module implementation which now deploys fine. I'd suggest to close this bug and open a feature request issue to add it back once the https://github.com/Azure/bicep/issues/6832 bug is fixed.

**Comment by MrMCake** [comment] 2022-07-17 20:58
@eriqua, agreed.

**Comment by eriqua** [comment] 2022-07-18 07:36
The feature request to add RBAC back is already open. Refer to #1543. Closing.

**Closed by eriqua** 2022-07-18 07:36 UTC
Labels: bug
