### ISSUE TITLE
[Feature Request]: Fix BCP335 across CARML modules

### ISSUE THREAD

**Issue by akata72** [Azure/ResourceModules#3167] opened 2023-05-04 18:42 UTC
### Description

In newer updates of Bicep the linter warning below appears across many modules in CARML. It would be nice if the @maxlength decorator could be added where suitable to make the tests clean and nice. :-) 

**Warning BCP335: The provided value has no configured maximum length and may be too long to assign to a target with a configured maximum length of**

**Comment by rahalan** [comment] 2023-05-09 15:10
Let's wait for Bicep v 0.17, if this is still existing

**Comment by akata72** [comment] 2023-05-10 21:09
Yes. I think this was relaxed in the latest version.

**Comment by rahalan** [comment] 2023-05-16 15:14
@akata72 can you please confirm that the issue is resolved with the new Bicep version?

**Comment by rahalan** [comment] 2023-05-30 15:10
@akata72 can you please confirm that the issue is resolved with the new Bicep version?

**Closed** 2023-06-05 15:16 UTC
Labels: enhancement
