### ISSUE TITLE
Cross module references discussion

### ISSUE THREAD

**Issue by rahalan** [Azure/ResourceModules#400] opened 2021-11-04 10:19 UTC
Should modules reference other modules (e.g. VM references PIP)? If yes, should the reference be local or via public reference?

**Comment by MariusStorhaug** [comment] 2021-11-10 18:48
Same issue but for LAW -> Solutions

**Comment by MrMCake** [comment] 2022-05-14 12:20
Closing as this is a duplicate of #905

**Closed by MrMCake** 2022-05-14 12:20 UTC
Labels: duplicate, enhancement, [cat] modules
