### ISSUE TITLE
[Updated] Module Readmes - Workout a testable solution for the description of array and object parameters

### ISSUE THREAD

**Issue by MariusStorhaug** [Azure/ResourceModules#1096] opened 2022-03-06 10:23 UTC
## Description

As most of the usage for object and array parameters are difficult to map out how to use, we should make it mandatory that these are in the readme files. Examples of what goes into an array, and what properties to use on a object parameter. Of course this only applies to the params we do not cover with child modules.

A suggestion would be to add a placeholder block such as below for all parameters of type array and object, excluding where we have a subfolder (child module) for it:
````md
### Parameter Usage: `<ParameterName>`

```bicep

```

````

**Comment by MrMCake** [comment] 2022-03-22 18:02
We should probably have an issue per resource type / provider

**Comment by MrMCake** [comment] 2022-05-28 19:45
Started the implementation in branch [users/alsehr/1096_paramUsage](https://github.com/Azure/ResourceModules/blob/users/alsehr/1096_paramUsage/utilities/tools/Set-ModuleReadMe.ps1).

It has however the issue that existing examples that are not in the parameter files may be overwritten & that comments are not translated into the generated example.

For example: 
![image](https://user-images.githubusercontent.com/5365358/170840658-4edf0d16-ec77-4b09-9003-78bd8cebb41a.png)

Further, fetching usage examples for child modules requires further engineering as it requires a dynamic drill down into the top-level module's parameter file.

**Comment by MrMCake** [comment] 2022-06-25 19:00
Duplicate of #1246 ?

**Comment by rahalan** [comment] 2022-08-04 15:37
@MrMCake will investigate further

**Comment by rahalan** [comment] 2022-09-29 15:35
Placeholder are not helping and manually written examples may be outdated. The team decides to have a preferably automated way to have working examples per complex parameter (or array parameter).

**Comment by eriqua** [comment] 2022-10-02 17:43
I'd strongly suggest to remove manually implemented parameter usage examples which are already used in deployment examples from the readme files until a good solution is found to automate them.

Not all parameter objects/arrays can be validated and for them the manually updated parameter usage snippets are for now good to be kept. Instead, the ones already used by deployment examples should be removed.

The reason is we may easily end up having two different snippets for the same parameter object/array: one in the parameter usage section (manually implemented once and usually never updated) and one in deployment examples (automatically retrieved and aligned with deployment validation tests).

An example is what we currently have for KeyVault networkAcls, which is quite error prone. From parameter usage:

```bicep
networkAcls: {
    bypass: 'AzureServices'
    defaultAction: 'Deny'
    virtualNetworkRules: [
        {
            subnetId: '/subscriptions/<<subscriptionId>>/resourceGroups/validation-rg/providers/Microsoft.Network/virtualNetworks/sxx-az-vnet-x-001/subnets/sxx-az-subnet-x-001'
        }
    ]
    ipRules: []
}
```

From deployment examples:

```bicep
networkAcls: {
      bypass: 'AzureServices'
      defaultAction: 'Deny'
      ipRules: []
      virtualNetworkRules: [
        {
          action: 'Allow'
          id: '<id>'
        }
      ]
    }
```

What showed in deployment examples should be the primary reference, as that gets continuously tested through module valitdation pipelines.

**Comment by AlexanderSehr** [comment] 2023-01-20 11:08
This will potentially go away with the future introduction of the user-defined types. cc: @eriqua 

I'd suggest to not invest work into this issue until the feature is implemented as it may render it redundant.

**Comment by AlexanderSehr** [comment] 2023-07-21 17:31
Closing in favor of the work for user-defined types.

**Closed by AlexanderSehr** 2023-07-21 17:31 UTC
Labels: documentation, enhancement, [cat] modules, [cat] needs further discussion, workshop feedback
